In [1]:
from glob import glob
import skimage.io as sk
import cv2
import pickle
from skimage.color import rgb2gray
from skimage.transform import resize
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("data.csv")
print(data.shape)

(741, 3)


In [3]:
print(data)

     Unnamed: 0                                           features  class
0             0  [18.973665961010276, 18.027756377319946, 17.08...      2
1             1  [43.18564576337837, 42.01190307520001, 40.0499...      2
2             2  [42.2965719651132, 41.10960958218893, 40.01249...      2
3             3  [43.104524124504614, 42.01190307520001, 41.012...      2
4             4  [43.73785545725808, 42.2965719651132, 41.04875...      2
..          ...                                                ...    ...
736         736  [43.104524124504614, 42.01190307520001, 41.012...      0
737         737  [44.04543109109048, 42.0, 41.048751503547585, ...      0
738         738  [10.44030650891055, 11.180339887498949, 12.041...      0
739         739  [38.01315561749642, 37.013511046643494, 36.055...      0
740         740  [43.18564576337837, 42.01190307520001, 41.0487...      0

[741 rows x 3 columns]


In [4]:
classes=data["class"]
print(classes)

0      2
1      2
2      2
3      2
4      2
      ..
736    0
737    0
738    0
739    0
740    0
Name: class, Length: 741, dtype: int64


In [9]:
col=data.columns
col

Index(['Unnamed: 0', 'features', 'class'], dtype='object')

In [10]:
col1=col[1:101]
print(col1)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [5]:
features=data['features']
print(features.shape)

(741,)


In [15]:
x1=0
p=[]
for i in features:
    i=np.array(i)
    i=i.astype(np.float64)
    p.append(i)


ValueError: could not convert string to float: '[18.973665961010276, 18.027756377319946, 17.08800749063506, 16.15549442140351, 14.866068747318506, 14.317821063276353, 13.892443989449804, 13.038404810405298, 12.206555615733702, 10.816653826391969, 9.433981132056603, 8.602325267042627, 7.810249675906654, 7.810249675906654, 8.06225774829855, 9.433981132056603, 8.06225774829855, 7.810249675906654, 7.0710678118654755, 7.810249675906654, 8.602325267042627, 8.94427190999916, 8.54400374531753, 8.246211251235321, 8.06225774829855, 8.0, 8.06225774829855, 8.246211251235321, 7.615773105863909, 6.324555320336759, 5.385164807134504, 4.123105625617661, 5.0, 6.082762530298219, 5.0990195135927845, 4.123105625617661, 3.1622776601683795, 4.123105625617661, 5.0, 4.123105625617661, 4.47213595499958, 5.385164807134504, 6.324555320336759, 7.615773105863909, 8.06225774829855, 8.602325267042627, 8.48528137423857, 9.219544457292887, 9.433981132056603, 8.94427190999916, 9.486832980505138, 10.44030650891055, 11.40175425099138, 12.165525060596439, 13.152946437965905, 14.035668847618199, 13.0, 13.038404810405298, 13.152946437965905, 14.142135623730951, 15.297058540778355, 15.524174696260024, 15.811388300841896, 16.15549442140351, 15.811388300841896, 15.524174696260024, 15.297058540778355, 14.142135623730951, 13.038404810405298, 13.0, 14.035668847618199, 14.142135623730951, 13.152946437965905, 12.36931687685298, 11.40175425099138, 10.44030650891055, 9.848857801796104, 9.433981132056603, 10.0, 9.219544457292887, 9.219544457292887, 8.602325267042627, 8.06225774829855, 8.54400374531753, 9.848857801796104, 11.180339887498949, 10.816653826391969, 11.40175425099138, 12.041594578792296, 12.041594578792296, 12.806248474865697, 13.601470508735444, 12.806248474865697, 12.727922061357855, 12.041594578792296, 11.40175425099138, 11.661903789690601, 11.180339887498949, 11.704699910719626, 10.44030650891055]'

In [19]:
print(len(features[2]))

1894


In [21]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Input,GlobalAveragePooling2D,BatchNormalization,GlobalAveragePooling1D
from keras.applications import DenseNet121
from keras.utils import to_categorical
from keras.models import Model
from sklearn.preprocessing import LabelEncoder
from keras.backend import clear_session
from sklearn.model_selection import train_test_split

In [8]:
x=to_categorical(classes)
lb=LabelEncoder()
x1=to_categorical(lb.fit_transform(classes))
print(x1)


[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0.

In [9]:
class_val=lb.fit_transform(classes)
print(class_val)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [112]:
print(features.shape)

(163, 100)


In [73]:
clear_session()
model=Sequential()
model.add(Input(shape=(100)))
model.add(Dense(256,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(256,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(156,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(256,activation="relu",kernel_initializer="he_uniform"))
model.add(BatchNormalization())
model.add(Dense(512,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(1024,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(256,activation="relu",kernel_initializer="he_uniform"))
model.add(BatchNormalization())
model.add(Dense(128,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(512,activation="relu",kernel_initializer="he_uniform"))
model.add(BatchNormalization())
model.add(Dense(256,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(512,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(128,activation="relu",kernel_initializer="he_uniform"))
model.add(BatchNormalization())
model.add(Dense(2056,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(1024,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(256,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(4,activation="softmax"))
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               25856     
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dense_2 (Dense)             (None, 156)               40092     
                                                                 
 dense_3 (Dense)             (None, 256)               40192     
                                                                 
 batch_normalization (BatchN  (None, 256)              1024      
 ormalization)                                                   
                                                                 
 dense_4 (Dense)             (None, 512)               131584    
                                                        

In [16]:
def ClsModel(n_classes=3, input_shape=(163,100,1)):

    model_d=DenseNet121(weights='imagenet',include_top=False, input_shape=(163,100,1)) 


    x=model_d.output


    x= GlobalAveragePooling2D()(x)

    x= BatchNormalization()(x)

    x= Dropout(0.5)(x)

    x= Dense(1024,activation='relu')(x) 

    x= Dense(512,activation='relu')(x) 

    x= BatchNormalization()(x)

    x= Dropout(0.5)(x)


    preds=Dense(n_classes,activation='softmax')(x) #
    model=Model(inputs=model_d.input,outputs=preds)
    return model

In [17]:
model=ClsModel(3,(163,100,1))

ValueError: The input must have 3 channels; Received `input_shape=(163, 100, 1)`

In [70]:
#features=np.array(features).reshape(145,100,1)
x_train,x_test,y_train,y_test=train_test_split(features,x1,test_size=0.3,random_state=42)


In [74]:
model.fit(x_train,y_train,verbose=1,batch_size=200,epochs=300,validation_data=[x_test,y_test])

Epoch 1/300
1/1 [==============================] - 7s 7s/step - loss: 2.1674 - accuracy: 0.2632 - val_loss: 134.0394 - val_accuracy: 0.2245
Epoch 2/300
1/1 [==============================] - 0s 188ms/step - loss: 5.8116 - accuracy: 0.3246 - val_loss: 115.3569 - val_accuracy: 0.2245
Epoch 3/300
1/1 [==============================] - 0s 178ms/step - loss: 8.7034 - accuracy: 0.3684 - val_loss: 67.8259 - val_accuracy: 0.2857
Epoch 4/300
1/1 [==============================] - 0s 183ms/step - loss: 4.5967 - accuracy: 0.3947 - val_loss: 36.8002 - val_accuracy: 0.2245
Epoch 5/300
1/1 [==============================] - 0s 179ms/step - loss: 1.6724 - accuracy: 0.5877 - val_loss: 54.0351 - val_accuracy: 0.2245
Epoch 6/300
1/1 [==============================] - 0s 181ms/step - loss: 1.6446 - accuracy: 0.3333 - val_loss: 47.5386 - val_accuracy: 0.2245
Epoch 7/300
1/1 [==============================] - 0s 175ms/step - loss: 1.1603 - accuracy: 0.4123 - val_loss: 28.9123 - val_accuracy: 0.2245
Epoch 8

KeyboardInterrupt: 

In [44]:
from sklearn.metrics import accuracy_score
pred=model.predict(x_test)
print(pred)

2/2 [==============================] - 0s 7ms/step
[[4.46619928e-01 2.60636210e-02 3.65417331e-01 1.61899194e-01]
 [4.01569605e-02 1.31290604e-03 9.58051980e-01 4.78139613e-04]
 [3.74480426e-01 2.01727636e-02 3.75653058e-01 2.29693651e-01]
 [6.62195757e-02 6.39304638e-01 1.18855517e-02 2.82590270e-01]
 [7.43736088e-01 6.47221517e-04 1.05207302e-01 1.50409341e-01]
 [2.81648606e-01 4.68323706e-03 7.13267863e-01 4.00283490e-04]
 [6.53272033e-01 2.59265840e-01 4.15185727e-02 4.59435768e-02]
 [2.87526231e-02 2.88291097e-01 4.77536488e-03 6.78180873e-01]
 [6.57477826e-02 4.23005287e-04 9.01544690e-01 3.22845094e-02]
 [9.79400754e-01 8.31850059e-03 6.59077289e-03 5.69008756e-03]
 [4.17267047e-02 8.00447464e-01 1.48622289e-01 9.20352153e-03]
 [7.40106963e-03 2.15615524e-04 9.64947402e-01 2.74359658e-02]
 [9.01690349e-02 1.34398997e-01 6.64174616e-01 1.11257434e-01]
 [4.83463518e-02 8.48282993e-01 5.16440580e-03 9.82062593e-02]
 [1.70050740e-01 5.71487285e-02 4.37201113e-01 3.35599333e-01]
 [5.

In [45]:
prediction=[]
for i in pred:
    prediction.append(np.argmax(i))
print(prediction)

[0, 2, 2, 1, 0, 2, 0, 3, 2, 0, 1, 2, 2, 1, 2, 1, 3, 2, 3, 0, 1, 0, 0, 0, 0, 3, 2, 1, 3, 3, 3, 1, 1, 2, 0, 2, 1, 1, 1, 3, 0, 3, 2, 2, 3, 0, 2, 0, 3]


In [46]:
expected=[]
for j in y_test:
    j=list(j)
    expected.append(j.index(1))
print(expected)


[3, 2, 3, 1, 2, 0, 3, 1, 2, 3, 0, 2, 0, 1, 0, 0, 3, 2, 3, 0, 1, 0, 0, 0, 0, 3, 2, 1, 3, 3, 3, 1, 1, 2, 0, 2, 1, 1, 1, 3, 0, 3, 2, 2, 3, 0, 2, 0, 3]


In [47]:
print(accuracy_score(expected,prediction))

0.7755102040816326
